name: flutterhw3
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/background.jpg
  - assets/images/sans.png
  - assets/images/papyrus.png
  - assets/images/toriel.png
  - assets/images/alphys.png
  - assets/images/undyne.png
  - assets/images/mettaton.png
  - assets/images/asgore.png
  - assets/images/flowey.png
  - assets/images/asriel.png
  - assets/images/chara.png
  - assets/images/area_ruins.jpg
  - assets/images/area_snowdin.jpg
  - assets/images/area_waterfall.jpg
  - assets/images/area_hotland.jpg
  - assets/images/area_core.jpg
  - assets/images/area_newhome.jpg

  - assets/audio/menu.mp3
  - assets/audio/sans.mp3
  - assets/audio/papyrus.mp3
  - assets/audio/toriel.mp3
  - assets/audio/alphys.mp3
  - assets/audio/undyne.mp3
  - assets/audio/mettaton.mp3
  - assets/audio/asgore.mp3
  - assets/audio/flowey.mp3
  - assets/audio/asriel.mp3
  - assets/audio/chara.mp3

  - assets/audio/MEGALOVANIA.mp3
  - assets/audio/once_upon_a_time.mp3
  - assets/audio/ruins.mp3
  - assets/audio/snowdin_town.mp3
  - assets/audio/waterfall.mp3
  - assets/audio/core.mp3
  - assets/audio/hopes_and_dreams.mp3

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/PixelFont.ttf
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
